### ISSUE TITLE
Не даёт зарегистрировать аккаунт

### ISSUE THREAD

**Issue by Rydupeek** [vladislav-puzyrev/vk-spammer-online#19]
Не возможно зарегистрироваться на данном сайте, помогите пожалуйста

**Comment by vladislav-puzyrev** [comment]
Здравствуйте, @Rydupeek.
 
 Регистрировать аккаунты нужно через вк, а затем добавлять в спамер. Так же учитывайте то, что браузер для работы спамера нужно запускать с выключенным cors (есть в инструкции).
