### ISSUE TITLE
Идеи по обновлению

### ISSUE THREAD

**Issue by vladislav-puzyrev** [vladislav-puzyrev/vk-spammer-online#4]
Я буду дальше заниматься спамером и хотел бы расписать здесь идеи по обновлению над которыми уже давно думал. Для начала вот таблица всех разделов (header) которые планируются в спамере после обновления:

| landing? | spamer | parser | modes | accounts | settings | storage |
|----------|--------|--------|-------|----------|----------|---------|

## Новый раздел - парсер (parser)
В парсере можно будет получать идентификаторы для рассылки с разных источников, например получить id всех друзей пользователя или id всех участников группы для рассылки конкретной аудитории.

## Новый раздел - режимы (modes)
Сейчас в спамере есть один необычный по сравнению с другими режим рассылки - **беседы с автовыходом**. Он более сложный чем остальные, поэтому я хочу создать для него и для бедующих сложных режимов (об этом написано далее) отдельный раздел в котором можно будет гибко настраивать их работу. Кроме того этот режим будет переименован в **партизан**. А обычный спамер будет содержать только простые **общие** режимы.

## Новый сложный режим - спам в ширину
Этот режим работает так:
1) Вы даете ему идентификатор пользователя и задаете сообщение, вложения.
2) Сообщение отсылается ему а затем запрашиваются все его друзья.
3) Далее сообщение отсылается всему списку друзей пользователя. И их друзья тоже добавляются в список рассылки, таким образом, имея очень много аккаунтов вы сможете отправить свое сообщение даже всем пользователям вк!

Кстати этот режим назван в честь алгоритма по которому он будет работать -  **поиск в ширину**.

## Новый сложный режим - камикадзе
Этот режим подходит для агрессивной рекламы на покупных аккаунтах. Суть заключается в том чтобы одним кликом имея купленный аккаунт установить ему выбранную аватарку, создать несколько записей на стене и начать рассылку сообщения всему списку друзей аккаунта. Еще я думаю над предварительным удалением всех старых записей со стены, фотографий, и рассылке сообщения всем друзьям друзей и тд как в режиме **спам в ширину**.

## Новый сложный режим - личка с ответом
Предложение @NetskyProject. Этот режим является копией обычного режима **личные сообщения**, только кроме вашего сообщения для рассылки есть возможность указать еще второе сообщение для ответа на возможно пришедшие сообщение от пользователя. Наверное это потребует использование websocket api - https://vk.com/dev/streaming_api_docs

## Новый раздел - хранилище (storage)
При использовании спамера я много раз сохранял себе на компьютер значения поля вложений, идентификаторов назначения и возможно самого сообщения чтобы потом снова использовать их в спамере а не вводить каждый раз вручную. Я думаю что будет удобно иметь раздел в котором можно будет создавать именованные текстовые файлы которые будут храниться прямо в браузере и иметь к ним доступ прямо из интерфейса спамера без необходимости сохранять а потом искать у себя на устройстве эти текстовые файлы.

## Новый раздел - аккаунты (accounts)
Работа с аккаунтами явно потребует отдельной страницы на которой можно будет добавлять разные настройки и метки для них.

## Новый раздел - настройки (settings)
Некоторые настройки которые я хочу вынести в этот раздел:
1) Очистка всех полей (из localStorage)
2) Кнопка включения уведомлений
3) ...

## Инструкции
Инструкции к каждому разделу как и сейчас буду находится в самом разделе снизу. Они точно будут в спамере, парсере и каждом из сложных режимов.

## Графики выпадения капчи
Мы планируем провести исследование и выяснить при каких интервалах отправки спама какая будет длительность выпадания капчи. После этого на странице спамера мы разместим наглядный график которому можно будет следовать из ваших потребностей рассылки, например если вы не хотите пользоваться сервисом anticaptcha.

## Состояние приложения
Предварительная структура состояния приложения. **[title]Mode** - это отдельное состояние для каждого сложного режима спама.
```javascript
{
'settings',
'accounts',
'spamer',
'parser',
'[title]Mode'
}
```

## Технологии PWA
В приложении планируется полностью адаптивная верстка для мобильных устройств и некоторые технологии PWA:
1) Возможность включения уведомлений (для важный события например ошибка капчи и тд)
2) Кеширование через serviceWorker
3) Установка на устройство

## Разные фичи
1) Загрузка текста (для разных полей) из локальных файлов и выгрузка назад (для парсера)
2) Индикация хода запросов в процентах
3) localStorage

## Next.js
Я бы очень хотел вывести этот спамер в поисковики в будущем, поэтому нужно переписать его на фреймворк [Next.js](https://nextjs.org/) для хорошей индексации html разметки и более хорошей производительности. Затем я куплю доменное имя и выложу его на полноценный хостинг, а на старый github pages добавлю какой-нибудь alert который будет говорить что эта страница устарела и просить перейти на новую.

Вот список зависимостей которые на мой взгляд будут лучшим выбором для проекта:
* material-ui - Работы многовато и заморачиваться с версткой распространенных элементов типо кнопок не хочется, займет много времени и сил, тем более в спамере дизайн второстепенная вещь.
* axios - Популярнейший http клиент, просто для удобства.
* formik - Он помогает обеспечивать flux круговорот на каждый символ для форм, чтобы не писать useState на каждое поле
* react-beautiful-dnd - Для drag'n'drop списков.
* redux-toolkit - Удобный сборник всего лучшего от redux. С ним можно писать меньше не нужного кода.
* redux-thunk - Является частью redux-toolkit. Я думал над redux-saga, но сталкивался с проблемой при ее использовании когда нужно было после работы saga worker запустить какой-то колбек, в thunk это делается просто и ее так же можно тестировать с jest.
* typescript - Для строгости и понятности кода.

## Proxy, user-agent
Сейчас в спамере есть одна очень большая проблема, все запросы на vk api идут через **один ip адрес**. Вот наглядное изображение как сейчас работает спамер:

![Демонстрация](https://user-images.githubusercontent.com/52296792/99152231-49e22380-26c2-11eb-8a1c-546f5f04889d.png)

Это делается так потому что vk не позволяет отправлять запросы к себе через браузер напрямую (защита CORS). Поэтому запрос к серверу api отправляется через бекенд а не браузер. Для решения проблемы одного и того же ip я нашел библиотеку [proxy-lists](https://github.com/chill117/proxy-lists) которая собирает список бесплатный открытых прокси с помощью которых можно будет делать запросы на сервер. К сожалению это добавит дополнительную временную задержку которая может быть важна например для режима **беседы с автовыходом**, но это необходимо.

Еще нужно будет потестить как вк реагирует на разные ip адреса идущие от одного аккаунта, может быть это будет считаться подозрительной активностью, тогда лучше будет привязывать к одному аккаунту только один ip адрес из прокси листа.

Для дополнительного снижения подозрительной активности можно еще подменять user-agent в http запросе.

## Дизайн
Нужен favicon, logo

**Comment by NetskyProject** [comment]
О, классные идеи. Мне очень понравились. Я бы добавил еще спам 2му сообщениями, отправляешь первое - ждешь ответ - тебе отвечают - отправляешь второе12.11.2020, 19:26, "Vladislav" <notifications@github.com>:
Я буду дальше заниматься спамером и хотел бы расписать здесь идеи по обновлению над которыми уже давно думал. Для начала вот таблица всех разделов (header) которые планируются в спамере после обновления:
landing?spamerparsermodesaccountssettingsstorage
Новый раздел - парсер (parser)
В парсере можно будет получать идентификаторы для рассылки с разных источников, например получить id всех друзей пользователя или id всех участников группы для рассылки конкретной аудитории.
Новый раздел - режимы (modes)
Сейчас в спамере есть один необычный по сравнению с другими режим рассылки - беседы с автовыходом. Он более сложный чем остальные, поэтому я хочу создать для него и для бедующих сложных режимов (об этом написано далее) отдельный раздел в котором можно будет гибко настраивать их работу. Кроме того этот режим будет переименован в партизан. А обычный спамер будет содержать только простые общие режимы.
Новый сложный режим - спам в ширину
Этот режим работает так:

Вы даете ему идентификатор пользователя и задаете сообщение, вложения.
Сообщение отсылается ему а затем запрашиваются все его друзья.
Далее сообщение отсылается всему списку друзей пользователя. И их друзья тоже добавляются в список рассылки, таким образом, имея очень много аккаунтов вы сможете отправить свое сообщение даже всем пользователям вк!

Кстати этот режим назван в честь алгоритма по которому он будет работать -  поиск в ширину.
Новый сложный режим - камикадзе
Этот режим подходит для агрессивной рекламы на покупных аккаунтах. Суть заключается в том чтобы одним кликом имея купленный аккаунт установить ему выбранную аватарку, создать несколько записей на стене и начать рассылку сообщения всему списку друзей аккаунта. Еще я думаю над предварительным удалением всех старых записей со стены, фотографий, и рассылке сообщения всем друзьям друзей и тд как в режиме спам в ширину.
Новый раздел - хранилище (storage)
При использовании спамера я много раз сохранял себе на компьютер значения поля вложений, идентификаторов назначения и возможно самого сообщения чтобы потом снова использовать их в спамере а не вводить каждый раз вручную. Я думаю что будет удобно иметь раздел в котором можно будет создавать именованные текстовые файлы которые будут храниться прямо в браузере и иметь к ним доступ прямо из интерфейса спамера без необходимости сохранять а потом искать у себя на устройстве эти текстовые файлы.
Новый раздел - аккаунты (accounts)
Работа с аккаунтами явно потребует отдельной страницы на которой можно будет добавлять разные настройки и метки для них.
Новый раздел - настройки (settings)
Некоторые настройки которые я хочу вынести в этот раздел:

Очистка всех полей (из localStorage)
Кнопка включения уведомлений
...

Инструкции
Инструкции к каждому разделу как и сейчас буду находится в самом разделе снизу. Они точно будут в спамере, парсере и каждом из сложных режимов.
Графики выпадения капчи
Мы планируем провести исследование и выяснить при каких интервалах отправки спама какая будет длительность выпадания капчи. После этого на странице спамера мы разместим наглядный график которому можно будет следовать из ваших потребностей.
Состояние приложения
Предварительная структура состояния приложения. [title]Mode - это отдельное состояние для каждого сложного режима спама.
{
'settings',
'accounts',
'spamer',
'parser',
'[title]Mode'
}
Технологии PWA
В приложении планируется полностью адаптивная верстка для мобильных устройств и некоторые технологии PWA:

Возможность включения уведомлений (для важный события например ошибка капчи и тд)
Кеширование через serviceWorker
Установка на устройство

Разные фичи

Загрузка текста (для разных полей) из локальных файлов и выгрузка назад (для парсера)
Индикация хода запросов в процентах
localStorage

Next.js
TODO

**Comment by vladislav-puzyrev** [comment]
@NetskyProject Привет! Рад это слышать) Мне кажется это тянет на еще один сложный режим рассылки, добавил твою идею в список.
