### ISSUE TITLE
Не работает авторизация.

### ISSUE THREAD

**Issue by Pererozhdennyy** [vladislav-puzyrev/vk-spammer-online#5]
## Описание ошибки
Просто не работает авторизация.

**Comment by vladislav-puzyrev** [comment]
VK API выбрасывает ошибку капчи, я думаю это из-за проблемы с одним и тем же ip на все запросы от спамера которую я описал подробно здесь - [#4 Идеи по обновлению](https://github.com/vladislav-puzyrev/vk-spamer-online/issues/4). Наверно кто-то сейчас активно спамил и у всех сейчас будет просить капчу))

![image](https://user-images.githubusercontent.com/52296792/99146807-2789df00-269d-11eb-92d7-6fcff3ee82f4.png)

Нужно написать proxy backend на node.js который будет привязывать каждый аккаунт к рандомному рабочему ip из открытых прокси листов, при этом если ip перестал быть доступен то менять его на другой рабочий.

Какого-то временного решения я здесь не вижу, но если вы знакомы с веб разработкой то можете запустить проект локально и изменить proxyURL в файле [./src/api/config.ts](https://github.com/vladislav-puzyrev/vk-spamer-online/blob/master/src/api/config.ts) на адрес другого прокси сервера, например можно использовать этот проект просто выложить его на heroku [cors-anywhere](https://github.com/Rob--W/cors-anywhere)

Ну или просто подождать придется.

**Comment by vladislav-puzyrev** [comment]
Проблема с одинаковым ip решена, теперь прокси сервер не используется.
